services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - "${TEST_BUILD}:/OnePlus8-Test:rw"
      - '${GIT_BUILD_A10}:/Android-10/OnePlus:rw'
      - '${GIT_BUILD_A11}:/Android-11/OnePlus:rw'
    container_name: Ubuntu-20.04
    hostname: Build-Environment
    tty: true
    stdin_open: true