services:
  ubuntu:
    image: scotthowson/ubuntu-touch-builder:latest
    privileged: true
    volumes:
      - '${GIT_BUILD_A10}:/Android-10/OnePlus:rw'
      - '${GIT_BUILD_TEST_A10}:/Android-10/OnePlus:rw'
    container_name: Ubuntu-20.04
    hostname: Build-Environment
    tty: true
    stdin_open: true